### ISSUE TITLE
Install VB + Vagrant as part of `init`

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-local-chassis#104]
A suggestion: on Mac OS hosts when `brew` is available, install VirtualBox / Vagrant for me.

**Comment by joehoyle** [comment]
`brew cask install virtual vagrant` for example.

**Comment by rmccue** [comment]
I can't emphasise how much I hate tools that attempt to do these sorts of things. Particularly with Brew, as I believe it will break VirtualBox's autoupdate capability.

I'd prefer us to detect it and prompt the user if anything.

I'm -1 on this, recommend close.

**Comment by joehoyle** [comment]
A prompt / docs to point me to the URL, or option to install via brew would be great!

**Comment by rmccue** [comment]
Closing as won't do.
