### ISSUE TITLE
Add convenience commands for viewing logs

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-chassis#106]
Local Server has the `logs` command which allows viewing logs for each service. For all our known services on Local Chassis suchas elasticsearch, tachyon etc... it would be nice to have a `composer chassis logs` command to quickly and easily view logs without having to know where they live and what secret incantations are required to view them like `sudo journalctl -u elasticsearch-es.service`.

**Comment by rmccue** [comment]
This is only a could, so closing out for now.
