### ISSUE TITLE
BUG: Altis v5 QA - composer chassis upgrade generates error

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-local-chassis#107]
Steps to reproduce:
1. Start with clean environment (no Chassis installed)
2. run `chassis init`
3. run `chassis upgrade`
4. see error

![Screen Shot 2020-10-23 at 2 09 07 PM](https://user-images.githubusercontent.com/991511/97054064-551db580-1541-11eb-8438-60d4b771c62c.png)

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
I can't reproduce this now. I think it was because Bronson had deleted the `master` branch upstream, but we resolved that with the patch in #114 to fetch the `main` branch instead.

**Comment by BronsonQuick** [comment]
Damn that Bronson guy doing the right thing and changing branch names too quickly 😜 @roborourke please let me know when we can delete `master` again upstream 🙏

**Comment by roborourke** [comment]
@BronsonQuick i think it should be ok to remove it again now, can’t really tell from the stats on github how many clones are for which branches but we can just handle any stragglers via support

**Comment by BronsonQuick** [comment]
@roborourke Perfect. Thank you Sir. I've deleted `master` now 🗑️
