### ISSUE TITLE
Give VirtualBox machine a better name

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-chassis#13]
In Virtualbox and others the chassis directory name and a generated hash ID is used to name the VM eg. `chassis_XXXXXXXXX`. This makes it hard to tell which project a VM belongs to.

We should clone Chassis to a directory like `chassis-<project-name>` and if possible add it to the `.gitignore` dynamically.

**Comment by roborourke** [comment]
cc @pdewouters

**Comment by rmccue** [comment]
We can do this by integrating into VB better; having the directory name consistent is useful for tooling, and we can correct these names instead.

**Comment by rmccue** [comment]
Let's handle this upstream in https://github.com/Chassis/Chassis/issues/628
