### ISSUE TITLE
Use HTTPS by default

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-chassis#17]
HTTPS should be used by default when setting up a local site using `composer chassis init`.

If it's not possible to do this by default, a command that looks something like `composer chassis secure` would be handy. [Laravel Valet provides this](https://laravel.com/docs/5.8/valet#securing-sites) and it's pretty neat.

**Comment by johnbillion** [comment]
The most up-to-date extension for HTTPS by the way is roborourke/chassis-openssl.

**Comment by roborourke** [comment]
So we can sort of default it by prompting another question post-provision. I'd rather avoid vagrant hooks as they suck. I've added a command to install the generated cert that can be used any time after the VM has been provisioned.

**Comment by joehoyle** [comment]
@roborourke is this looking on track for v2? I'm assuming perhaps not, so maybe we want to punt?

**Comment by roborourke** [comment]
Just needs the windows portion testing. Good otherwise
