### ISSUE TITLE
Update to default to PHP 8

### ISSUE THREAD

**Issue by veselala** [humanmade/altis-local-chassis#187]
Acceptance criteria:

- [ ] Use PHP 8 by default
- [ ] Update docs for how to configure PHP version

**Comment by roborourke** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Altis-5c378365e15075539771e4e3/issues/humanmade/altis-local-chassis/187?planning-poker) with ZenHub @mikelittle @robindevitt @shadyvb

**Comment by veselala** [comment]
We'll be deprecating local chassis with v.12 so no update to PHP 8 will be needed.
