### ISSUE TITLE
Support for Chassis and extension updates

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-chassis#31]
Once Chassis has been checked out and set up you have to fetch updates to chassis and its extensions manually right now.

Either or both of the following additions would improve the developer experience here:

- Add a command `composer chassis update`
  - pulls latest master
  - updates extensions to latest versions
  - re-provisions the machine
- Do the above steps but on `composer update` if this package version changes

Make sense to you @rmccue ?

**Comment by BronsonQuick** [comment]
@roborourke I've got https://github.com/Chassis/Chassis/pull/504 sitting upstream to handle this. I've just been waiting for code review for it. Feel free to review it for me if you like and we can handle it in Chassis core instead.

**Comment by roborourke** [comment]
@BronsonQuick awesome :)

Gonna start digging into how best to manage the roll out / updates from our end here. The Bionic Beaver update is pretty major!

**Comment by roborourke** [comment]
So actually fixed this in #51 ! Good times
