### ISSUE TITLE
When re-creating a box from scratch VirtualBox returns errors

### ISSUE THREAD

**Issue by stuartshields** [humanmade/altis-local-chassis#35]
So currently when you give a `VirtualBox machine a better name` and delete the original repo and try to re-create the box VirtualBox returns the following errors:

```
A VirtualBox machine with the name 'custom.local' already exists.
```

This is because in the `VirtualBox VMs` folder, the machine is called `custom.local`, the issue is that this isn't a unique folder name.

Do not delete the folder and try again, as this will cause more critical errors:
```
Stderr: VBoxManage: error: Failed to create the VirtualBox object!
VBoxManage: error: Cannot register the hard disk '/Users/stuartshields/VirtualBox VMs/custom.local/ubuntu-16.04-amd64-disk001.vmdk' {810ea9b3-5e2d-45ca-88d9-55e6ec03e8db} because a hard disk '/Users/stuartshields/VirtualBox VMs/custom.local/ubuntu-16.04-amd64-disk001.vmdk' with UUID {0c62091e-58cf-44ff-9af1-a1c8d5c856cf} already exists
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component VirtualBoxWrap, interface IVirtualBox
```

If you then try and open up VirtualBox GUI, it will crash out:
```
Failed to acquire the VirtualBox COM object
```

The only way to fix this is to do the following:
- Go into `/Users/stuartshields/Library/VirtualBox`
- Delete `VirtualBox.xml` and try again.

Solution is to make the custom.local folder inside of `VirtualBox VMs` have a unique folder name so when a user attempts to re-create a project they don't run into the same issue as outlined above.

**Comment by roborourke** [comment]
So I’m clear on what happened:

- you had the project set up and vm created
- deleted the project directory 
- set up the project again 

I think we could append a unique ID after the defined machine name to help avoid this kind of error but I also see an opportunity to provide faq / troubleshooting docs for best practices with VMs. For example when a VM becomes orphaned and can’t be destroyed via a vagrant command use the virtual box gui to do so. In addition avoid deleting a project directory without first destroying the associated vm.

Devs might end up with with a ton of unused VMs and not be sure how best to clean them up so my personal view is that the error is useful, but we need to make sure everyone knows how to solve it. We might be able to catch the specific error and suggest the solution or even delete the old one programmatically

**Comment by stuartshields** [comment]
@roborourke Actually, I had 1 project built using 99co.local as I was wanting to create another build based on some additional changes to make sure the build process worked. If that makes sense?

**Comment by roborourke** [comment]
@stuartshields ahh cool, cheers for the clarification! It sounds like a not super common occurrence but one we should factor in.

We can add a timestamp / date to the machine name. The main thing is you can still see `altis.local` or whatever to identify the VM in VirtualBox GUI.

**Comment by rmccue** [comment]
I haven't heard anyone else hitting this issue. Let's close this out, but reopen if we see it again.
