### ISSUE TITLE
Restrict direct access to PHP files inside content

### ISSUE THREAD

**Issue by pdewouters** [humanmade/altis-local-chassis#37]
Because there is a restriction on direct access to PHP files on Altis - for example as an endpoint for an ajax request, we should also apply this restriction to the local environment

https://github.com/humanmade/infrastructure-config/blob/master/config/nginx-vhost-appserver.conf#L41-L44

**Comment by kadamwhite** [comment]
@rmccue any general direction on how we would be able to set these options from a module like this?

**Comment by rmccue** [comment]
The best way to do this would be to include it in the [nginx additions](https://github.com/humanmade/platform_chassis_extension/blob/master/modules/platform_chassis_extension/manifests/init.pp) in platform_chassis_extension. We'll want to break it out from that inline string to a template file though.

**Comment by jennybeaumont** [comment]
Closing as wont have
