### ISSUE TITLE
Show User/Pass/URL on composer chassis start

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-local-chassis#40]
Local server generates terminal output for the username/password/URL when running `composer local-server start` but `composer chassis start` does not

**Comment by rmccue** [comment]
Chassis does this on initial provision; should we also show it on subsequent starts?

**Comment by tomjn** [comment]
The URL on start would be handy

**Comment by roborourke** [comment]
It's easy to miss on `init` because the output isn't colourised
