### ISSUE TITLE
Search-replace on composer chassis secure

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-chassis#49]
Right now some people experience unwanted redirects from HTTPS to HTTP. When running `composer chassis secure` we could go a stage further and do the search replace to ensure the https URL is the canonical one.

props @kucrut for reporting.

This is difficult as we need to distinguish internal links and external links.

Acceptance criteria:

- [ ] After running `composer chassis secure` and accepting the initial prompt to add the key, a 2nd prompt question is shown to say `Would you like to replace http:// with https:// in the database?`
- [ ] If yes to above run a search replace command to update instances of `http://` to `https://`
- [ ] Search replace must only include `wp_options`, `wp_blogs`, `wp_blogmeta`, `wp_sites` and `wp_sitemeta` tables

**Comment by johnbillion** [comment]
Any reason not to do something like this?

```
foreach extra.altis.modules.local-chassis.hosts as host
    wp search-replace http://{host} https://{host}
```

**Comment by PriyaBhatia0210** [comment]
Closing as we wont do this rn.
