### ISSUE TITLE
Add an SSH alias

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-local-chassis#70]
I type out `vagrant ssh` a lot and so I keep typing out `composer chassis ssh` from force of habit, getting it wrong, then typing `composer chassis shell`. It'd be nice if they both worked

Acceptance criteria:

- [ ] Typing `composer chassis ssh` has the same result as `composer chassis shell`

**Comment by roborourke** [comment]
Yeah I do this with `halt`/`stop` all the time too. Think this is a good first issue
