### ISSUE TITLE
restart/reload commands don't exist

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-chassis#83]
The [Available Commands documentation](https://github.com/humanmade/altis-local-chassis/tree/master/docs#available-commands) lists `restart\reload`, but these commands do not exist.

**Comment by johnbillion** [comment]
Same for `ssh` ([reported here](https://github.com/humanmade/altis-local-chassis/issues/84)) and `destroy`.

`init`, `start`, `stop`, `status`, `shell`, `update` all confirmed as working.

**Comment by kadamwhite** [comment]
@rmccue I am seeing this too. Could this be a docs version mismatch? has there been a release since these were added?

**Comment by rmccue** [comment]
Ah yes, this is the in-development version of the docs.

Consult the [live documentation for v3 instead](https://www.altis-dxp.com/resources/docs/local-chassis/#available-commands).

**Comment by roborourke** [comment]
Closing this out. For reference @johnbillion @kadamwhite if you want to see the docs specific to your version you can do so in the admin of your local install under the admin bar Altis logo dropdown menu, otherwise consult the website docs for the latest stable version.
