### ISSUE TITLE
ssh command doesn't exist

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-chassis#84]
The [Available Commands documentation](https://github.com/humanmade/altis-local-chassis/tree/master/docs#available-commands) lists `ssh\shell`, but the `ssh` command does not exist, while `shell` does.

**Comment by roborourke** [comment]
This is a version mismatch in terms of the docs you're looking at and the version you're working with.

The commands definitely exist here in `master`:

https://github.com/humanmade/altis-local-chassis/blob/master/inc/class-command.php#L114-L116

Consult the docs either from the appropriate branch on this repo eg. `v3-branch`, the WP admin area on your local under the top bar altis logo or on altis-dxp.com for the current stable release docs.
